### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by netbuffer** [meolu/walden#2]
![bc](https://cloud.githubusercontent.com/assets/7599915/10415217/c7ce24d0-7022-11e5-82b3-67f68aa1c807.JPG)
部署后直接访问就抛出这个错，怎么破

**Comment by meolu** [comment]
@netbuffer 
修正了，更新下`git pull`，再刷新看看？

**Comment by netbuffer** [comment]
@meolu  PHP Fatal error:  **Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in walden\Bootstrap.php on line 378** 又出现这个了

**Comment by meolu** [comment]
@netbuffer 
这个应该是没有添加ssh-key到git造成的，我已经把错误提示增强了，重新更新下`git pull`

**Comment by netbuffer** [comment]
@meolu 
![cuo](https://cloud.githubusercontent.com/assets/7599915/10422312/434e1dd6-70eb-11e5-8b68-6af0dffc9459.png)

**Comment by netbuffer** [comment]
@meolu 怎么处理？

**Comment by meolu** [comment]
@netbuffer 
不好意思，把你给忘了：(
最近在忙walle项目，你是在win下部署的么？

**Comment by meolu** [comment]
如果是win下的话，是不行的，需要bash环境

**Comment by netbuffer** [comment]
@meolu  额，好吧
